# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: run_mode_conf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='run_mode_conf.proto',
  package='apollo.cyber.proto',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13run_mode_conf.proto\x12\x12\x61pollo.cyber.proto\"C\n\x08\x44\x65\x62ugMsg\x12\x37\n\ndebug_mode\x18\x01 \x01(\x0e\x32\x1d.apollo.cyber.proto.DebugMode:\x04none\"\x89\x01\n\x0bRunModeConf\x12;\n\x08run_mode\x18\x01 \x01(\x0e\x32\x1b.apollo.cyber.proto.RunMode:\x0cMODE_REALITY\x12=\n\nclock_mode\x18\x02 \x01(\x0e\x32\x1d.apollo.cyber.proto.ClockMode:\nMODE_CYBER*0\n\x07RunMode\x12\x10\n\x0cMODE_REALITY\x10\x00\x12\x13\n\x0fMODE_SIMULATION\x10\x01**\n\tClockMode\x12\x0e\n\nMODE_CYBER\x10\x00\x12\r\n\tMODE_MOCK\x10\x01*>\n\tDebugMode\x12\x08\n\x04none\x10\x00\x12\x1c\n\x18singleframe_step_forward\x10\x01\x12\t\n\x05pause\x10\x02'
)

_RUNMODE = _descriptor.EnumDescriptor(
  name='RunMode',
  full_name='apollo.cyber.proto.RunMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODE_REALITY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODE_SIMULATION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=252,
  serialized_end=300,
)
_sym_db.RegisterEnumDescriptor(_RUNMODE)

RunMode = enum_type_wrapper.EnumTypeWrapper(_RUNMODE)
_CLOCKMODE = _descriptor.EnumDescriptor(
  name='ClockMode',
  full_name='apollo.cyber.proto.ClockMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODE_CYBER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODE_MOCK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=302,
  serialized_end=344,
)
_sym_db.RegisterEnumDescriptor(_CLOCKMODE)

ClockMode = enum_type_wrapper.EnumTypeWrapper(_CLOCKMODE)
_DEBUGMODE = _descriptor.EnumDescriptor(
  name='DebugMode',
  full_name='apollo.cyber.proto.DebugMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='singleframe_step_forward', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='pause', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=346,
  serialized_end=408,
)
_sym_db.RegisterEnumDescriptor(_DEBUGMODE)

DebugMode = enum_type_wrapper.EnumTypeWrapper(_DEBUGMODE)
MODE_REALITY = 0
MODE_SIMULATION = 1
MODE_CYBER = 0
MODE_MOCK = 1
none = 0
singleframe_step_forward = 1
pause = 2



_DEBUGMSG = _descriptor.Descriptor(
  name='DebugMsg',
  full_name='apollo.cyber.proto.DebugMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='debug_mode', full_name='apollo.cyber.proto.DebugMsg.debug_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=110,
)


_RUNMODECONF = _descriptor.Descriptor(
  name='RunModeConf',
  full_name='apollo.cyber.proto.RunModeConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='run_mode', full_name='apollo.cyber.proto.RunModeConf.run_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock_mode', full_name='apollo.cyber.proto.RunModeConf.clock_mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=250,
)

_DEBUGMSG.fields_by_name['debug_mode'].enum_type = _DEBUGMODE
_RUNMODECONF.fields_by_name['run_mode'].enum_type = _RUNMODE
_RUNMODECONF.fields_by_name['clock_mode'].enum_type = _CLOCKMODE
DESCRIPTOR.message_types_by_name['DebugMsg'] = _DEBUGMSG
DESCRIPTOR.message_types_by_name['RunModeConf'] = _RUNMODECONF
DESCRIPTOR.enum_types_by_name['RunMode'] = _RUNMODE
DESCRIPTOR.enum_types_by_name['ClockMode'] = _CLOCKMODE
DESCRIPTOR.enum_types_by_name['DebugMode'] = _DEBUGMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DebugMsg = _reflection.GeneratedProtocolMessageType('DebugMsg', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGMSG,
  '__module__' : 'run_mode_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.cyber.proto.DebugMsg)
  })
_sym_db.RegisterMessage(DebugMsg)

RunModeConf = _reflection.GeneratedProtocolMessageType('RunModeConf', (_message.Message,), {
  'DESCRIPTOR' : _RUNMODECONF,
  '__module__' : 'run_mode_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.cyber.proto.RunModeConf)
  })
_sym_db.RegisterMessage(RunModeConf)


# @@protoc_insertion_point(module_scope)
